### ISSUE TITLE
Firebase database, config syntaxis

### ISSUE THREAD

**Issue by askerrr** [vekexasia/dpos-telegram-bot#1]
Hi vekexasia, thank you for awesome soft! I've tried to install it on my server, but I've got this error:

```
:~/dpos-telegram-bot$ node_modules/.bin/ts-node src/index.ts

dpos-telegram-bot/node_modules/firebase-admin/lib/utils/error.js:39
        var _this = _super.call(this, errorInfo.message) || this;
                           ^
Error: Invalid Firebase app options passed as the first argument to initializeApp() for the app named "[DEFAULT]". The "credential" property must be an object which implements the Credential interface.
    at FirebaseAppError.Error (native)
    at FirebaseAppError.FirebaseError [as constructor] (/home/admin/dpos-telegram-bot/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/home/admin/dpos-telegram-bot/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/home/admin/dpos-telegram-bot/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at new FirebaseApp (/home/admin/dpos-telegram-bot/node_modules/firebase-admin/lib/firebase-app.js:198:19)
    at FirebaseNamespaceInternals.initializeApp (/home/admin/dpos-telegram-bot/node_modules/firebase-admin/lib/firebase-namespace.js:80:19)
    at FirebaseNamespace.initializeApp (/home/admin/dpos-telegram-bot/node_modules/firebase-admin/lib/firebase-namespace.js:362:30)
    at Object.<anonymous> (/home/admin/dpos-telegram-bot/src/models/firebasemodel.ts:6:10)
    at Module._compile (module.js:577:32)
    at Module.m._compile (/home/admin/dpos-telegram-bot/node_modules/ts-node/src/index.ts:422:23)
```

But I'm not sure about data syntaxis in config :

```
firebase:
  type: service_account
  project_id: super-bot
  private_key_id: e0ca29289keyhere7a95f34
  private_key: -----BEGIN PRIVATE KEY-----keyhere\n-----END PRIVATE KEY-----\n
  client_email: firebase-adminsdk-na1zv@super-bot.iam.gserviceaccount.com
  client_id: 110021keyhere042127
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://accounts.google.com/o/oauth2/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-na1zv%40super-bot.iam.gserviceaccount.com
  databaseURL: https://super-bot.firebaseio.com
telegram:
  token: 575keyhere685:AAFMdOQMrBkeyhereQYHROFe2Yo
  ownerId: 53keyhere33
```
I've checked it, and it's valid YAML. Maybe I'm shoud to add some parametrs to Firebase Database before launching? I'm sorry for dumb questions.
